
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 06 16:08:48 CST 2011
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 4;
  public static final int FUNCTION = 2;
  public static final int GE = 10;
  public static final int UMINUS = 42;
  public static final int LPAREN = 25;
  public static final int INT = 43;
  public static final int ARRAY = 14;
  public static final int FOR = 16;
  public static final int MINUS = 13;
  public static final int RPAREN = 26;
  public static final int AND = 35;
  public static final int SEMICOLON = 28;
  public static final int LT = 11;
  public static final int TYPE = 15;
  public static final int NIL = 8;
  public static final int IN = 21;
  public static final int OR = 7;
  public static final int COMMA = 19;
  public static final int PLUS = 36;
  public static final int ASSIGN = 23;
  public static final int IF = 27;
  public static final int ID = 45;
  public static final int DOT = 24;
  public static final int LE = 20;
  public static final int OF = 12;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int NEQ = 32;
  public static final int BREAK = 34;
  public static final int EQ = 41;
  public static final int LBRACK = 30;
  public static final int TIMES = 18;
  public static final int COLON = 5;
  public static final int LBRACE = 37;
  public static final int ELSE = 6;
  public static final int RBRACK = 31;
  public static final int TO = 17;
  public static final int WHILE = 29;
  public static final int LET = 39;
  public static final int THEN = 40;
  public static final int RBRACE = 38;
  public static final int END = 22;
  public static final int STRING = 44;
  public static final int GT = 3;
  public static final int VAR = 33;
  public static final int DO = 9;
}

