/* The following code was generated by JFlex 1.4.3 on 2/8/11 2:41 PM */

package parse;
import java_cup.runtime.*;
import java.util.*;

import errormsg.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/8/11 2:41 PM from the specification file
 * <tt>tiger.flex</tt>
 */
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\1\0\1\56"+
    "\3\0\1\54\1\0\1\36\1\37\1\47\1\45\1\33\1\46\1\44"+
    "\1\50\12\6\1\34\1\35\1\52\1\51\1\53\1\0\1\61\32\62"+
    "\1\40\1\57\1\41\1\60\1\5\1\0\1\7\1\12\1\24\1\15"+
    "\1\13\1\22\1\4\1\27\1\26\1\4\1\14\1\17\1\4\1\21"+
    "\1\16\1\30\1\4\1\10\1\20\1\25\1\23\1\31\1\32\1\4"+
    "\1\11\1\4\1\42\1\55\1\43\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\3\2\1\3\1\4\14\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\2\32\1\33\1\1\3\34\4\3"+
    "\1\35\1\36\5\3\1\37\1\3\1\40\1\41\2\3"+
    "\1\42\1\43\1\44\1\45\1\46\1\32\2\0\1\47"+
    "\1\50\1\51\1\52\1\0\1\53\1\54\3\3\1\55"+
    "\1\56\1\57\1\60\3\3\1\61\1\3\1\0\1\62"+
    "\2\3\1\63\1\3\1\64\1\65\1\3\1\66\1\67"+
    "\1\3\1\70\2\3\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\377\0\231\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\u0396\0\u03c9\0\231\0\u03fc\0\231"+
    "\0\231\0\231\0\231\0\231\0\231\0\231\0\231\0\231"+
    "\0\231\0\231\0\u042f\0\231\0\u0462\0\u0495\0\231\0\231"+
    "\0\231\0\231\0\u04c8\0\u04fb\0\231\0\u052e\0\231\0\u0561"+
    "\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0132\0\u0132\0\u0693"+
    "\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0132\0\u0792\0\u0132\0\u0132"+
    "\0\u07c5\0\u07f8\0\231\0\231\0\231\0\231\0\231\0\231"+
    "\0\u082b\0\u085e\0\231\0\231\0\231\0\231\0\u0891\0\231"+
    "\0\231\0\u08c4\0\u08f7\0\u092a\0\u0132\0\u0132\0\u0132\0\u0132"+
    "\0\u095d\0\u0990\0\u09c3\0\u0132\0\u09f6\0\u0a29\0\231\0\u0a5c"+
    "\0\u0a8f\0\u0132\0\u0ac2\0\u0132\0\u0132\0\u0af5\0\u0132\0\u0132"+
    "\0\u0b28\0\u0132\0\u0b5b\0\u0b8e\0\u0132";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\1\10\1\4\1\11\1\12"+
    "\2\10\1\13\1\14\1\10\1\15\1\16\1\17\1\10"+
    "\1\20\1\21\2\10\1\22\1\23\2\10\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\3\4\1\10\1\52\1\53"+
    "\1\54\53\52\1\55\1\56\3\52\47\57\1\60\1\61"+
    "\12\57\65\0\1\7\61\0\1\7\65\0\27\10\27\0"+
    "\1\10\6\0\1\11\60\0\4\10\1\62\22\10\27\0"+
    "\1\10\4\0\4\10\1\63\22\10\27\0\1\10\4\0"+
    "\13\10\1\64\1\10\1\65\11\10\27\0\1\10\4\0"+
    "\12\10\1\66\14\10\27\0\1\10\4\0\16\10\1\67"+
    "\10\10\27\0\1\10\4\0\7\10\1\70\17\10\27\0"+
    "\1\10\4\0\22\10\1\71\4\10\27\0\1\10\4\0"+
    "\12\10\1\72\4\10\1\73\7\10\27\0\1\10\4\0"+
    "\5\10\1\74\4\10\1\75\10\10\1\76\3\10\27\0"+
    "\1\10\4\0\15\10\1\77\1\100\10\10\27\0\1\10"+
    "\4\0\3\10\1\101\23\10\27\0\1\10\4\0\23\10"+
    "\1\102\3\10\27\0\1\10\51\0\1\103\60\0\1\104"+
    "\64\0\1\105\1\0\1\106\60\0\1\107\13\0\1\110"+
    "\61\0\1\110\62\0\3\111\2\0\1\112\12\0\1\113"+
    "\3\0\1\114\30\0\1\115\1\116\1\117\52\0\1\120"+
    "\61\0\1\121\17\0\4\10\1\122\22\10\27\0\1\10"+
    "\4\0\7\10\1\123\17\10\27\0\1\10\4\0\14\10"+
    "\1\124\12\10\27\0\1\10\4\0\11\10\1\125\15\10"+
    "\27\0\1\10\4\0\21\10\1\126\5\10\27\0\1\10"+
    "\4\0\13\10\1\127\13\10\27\0\1\10\4\0\4\10"+
    "\1\130\22\10\27\0\1\10\4\0\15\10\1\131\11\10"+
    "\27\0\1\10\4\0\24\10\1\132\2\10\27\0\1\10"+
    "\4\0\7\10\1\133\17\10\27\0\1\10\4\0\4\10"+
    "\1\134\22\10\27\0\1\10\4\0\22\10\1\135\4\10"+
    "\27\0\1\10\1\0\3\111\53\0\1\7\11\0\1\136"+
    "\61\0\1\137\32\0\2\137\15\0\4\137\4\0\3\10"+
    "\1\140\23\10\27\0\1\10\4\0\3\10\1\141\23\10"+
    "\27\0\1\10\4\0\7\10\1\142\17\10\27\0\1\10"+
    "\4\0\20\10\1\143\6\10\27\0\1\10\4\0\7\10"+
    "\1\144\17\10\27\0\1\10\4\0\15\10\1\145\11\10"+
    "\27\0\1\10\4\0\13\10\1\146\13\10\27\0\1\10"+
    "\6\0\1\52\60\0\5\10\1\147\21\10\27\0\1\10"+
    "\4\0\10\10\1\150\16\10\27\0\1\10\4\0\21\10"+
    "\1\151\5\10\27\0\1\10\4\0\7\10\1\152\17\10"+
    "\27\0\1\10\4\0\22\10\1\153\4\10\27\0\1\10"+
    "\4\0\12\10\1\154\14\10\27\0\1\10\4\0\15\10"+
    "\1\155\11\10\27\0\1\10";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3009];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\2\1\1\11\16\1\1\11\1\1\13\11"+
    "\1\1\1\11\2\1\4\11\2\1\1\11\1\1\1\11"+
    "\23\1\6\11\2\0\4\11\1\0\2\11\14\1\1\0"+
    "\1\11\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	StringBuffer string = new StringBuffer();
	int stringBegin = 0;
	int commentDepth = 0;
	ErrorMsg errorSender;

	private Symbol symbol(int type)
	{
		return new Symbol(type, yychar, yychar + yylength());
	}
	private Symbol symbol(int type, Object value)
	{
		return new Symbol(type, yychar, yychar + yylength(),value);
	}
	private Symbol symbol(int type, Object value, int pos)
	{
		return new Symbol(type, pos, yychar + yylength(),value);
	}
	public Lexer(java.io.InputStream in, ErrorMsg aErrorMsg)
	{
		this(in);
		errorSender = aErrorMsg;
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 43: 
          { commentDepth--; if(commentDepth == 0)yybegin(YYINITIAL);
          }
        case 58: break;
        case 1: 
          { errorSender.error(yychar,"illegal character");return symbol(Sym.error);
          }
        case 59: break;
        case 30: 
          { return symbol(Sym.OF);
          }
        case 60: break;
        case 31: 
          { return symbol(Sym.TO);
          }
        case 61: break;
        case 9: 
          { return symbol(Sym.RPAREN);
          }
        case 62: break;
        case 21: 
          { return symbol(Sym.GT);
          }
        case 63: break;
        case 45: 
          { return symbol(Sym.END);
          }
        case 64: break;
        case 40: 
          { string.append("\t");
          }
        case 65: break;
        case 20: 
          { return symbol(Sym.LT);
          }
        case 66: break;
        case 12: 
          { return symbol(Sym.LBRACE);
          }
        case 67: break;
        case 22: 
          { return symbol(Sym.AND);
          }
        case 68: break;
        case 34: 
          { return symbol(Sym.ASSIGN);
          }
        case 69: break;
        case 42: 
          { string.append("\\");
          }
        case 70: break;
        case 27: 
          { yybegin(YYINITIAL);return symbol(Sym.STRING,string.toString(),stringBegin);
          }
        case 71: break;
        case 15: 
          { return symbol(Sym.PLUS);
          }
        case 72: break;
        case 54: 
          { return symbol(Sym.ARRAY);
          }
        case 73: break;
        case 24: 
          { string.setLength(0);yybegin(STRING);stringBegin = yychar;
          }
        case 74: break;
        case 50: 
          { string.append((char)((int)yytext().charAt(2)-64));
          }
        case 75: break;
        case 52: 
          { return symbol(Sym.TYPE);
          }
        case 76: break;
        case 3: 
          { return symbol(Sym.ID,yytext());
          }
        case 77: break;
        case 29: 
          { return symbol(Sym.DO);
          }
        case 78: break;
        case 17: 
          { return symbol(Sym.TIMES);
          }
        case 79: break;
        case 51: 
          { return symbol(Sym.ELSE);
          }
        case 80: break;
        case 41: 
          { string.append("\"");
          }
        case 81: break;
        case 37: 
          { return symbol(Sym.NEQ);
          }
        case 82: break;
        case 10: 
          { return symbol(Sym.LBRACK);
          }
        case 83: break;
        case 6: 
          { return symbol(Sym.COLON);
          }
        case 84: break;
        case 53: 
          { return symbol(Sym.THEN);
          }
        case 85: break;
        case 49: 
          { return symbol(Sym.VAR);
          }
        case 86: break;
        case 56: 
          { return symbol(Sym.WHILE);
          }
        case 87: break;
        case 55: 
          { return symbol(Sym.BREAK);
          }
        case 88: break;
        case 33: 
          { return symbol(Sym.IF);
          }
        case 89: break;
        case 8: 
          { return symbol(Sym.LPAREN);
          }
        case 90: break;
        case 28: 
          { /* do nothing*/
          }
        case 91: break;
        case 23: 
          { return symbol(Sym.OR);
          }
        case 92: break;
        case 32: 
          { return symbol(Sym.IN);
          }
        case 93: break;
        case 35: 
          { commentDepth++; yybegin(COMMENT);
          }
        case 94: break;
        case 19: 
          { return symbol(Sym.EQ);
          }
        case 95: break;
        case 26: 
          { errorSender.error(yychar,"string not closed");return symbol(Sym.error);
          }
        case 96: break;
        case 13: 
          { return symbol(Sym.RBRACE);
          }
        case 97: break;
        case 48: 
          { return symbol(Sym.FOR);
          }
        case 98: break;
        case 7: 
          { return symbol(Sym.SEMICOLON);
          }
        case 99: break;
        case 46: 
          { return symbol(Sym.LET);
          }
        case 100: break;
        case 39: 
          { string.append("\n");
          }
        case 101: break;
        case 47: 
          { return symbol(Sym.NIL);
          }
        case 102: break;
        case 44: 
          { commentDepth++;
          }
        case 103: break;
        case 25: 
          { string.append(yytext());
          }
        case 104: break;
        case 16: 
          { return symbol(Sym.MINUS);
          }
        case 105: break;
        case 38: 
          { return symbol(Sym.GE);
          }
        case 106: break;
        case 4: 
          { return symbol(Sym.INT,new Integer(yytext()));
          }
        case 107: break;
        case 57: 
          { return symbol(Sym.FUNCTION);
          }
        case 108: break;
        case 18: 
          { return symbol(Sym.DIVIDE);
          }
        case 109: break;
        case 5: 
          { return symbol(Sym.COMMA);
          }
        case 110: break;
        case 36: 
          { return symbol(Sym.LE);
          }
        case 111: break;
        case 11: 
          { return symbol(Sym.RBRACK);
          }
        case 112: break;
        case 14: 
          { return symbol(Sym.DOT);
          }
        case 113: break;
        case 2: 
          { 
          }
        case 114: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { 	if(yystate() == COMMENT){
				 errorSender.error(yychar,"comment is not closed");
				 return symbol(Sym.error);
	}
	if(yystate() == STRING){
				 errorSender.error(yychar,"string is not closed");
				 return symbol(Sym.error);
	}
	return symbol(Sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
